version: '3.1'

services:
  livemart-vex-hugo:
    image: livemart-vex-hugo:latest
    ports:
      - 1313:1313
    entrypoint: [ "hugo", "server", "--themesDir", "../..", "--baseUrl=https://demo-hugo.livemart.xyz", "--appendPort=false" ]
    working_dir: "/root/projects/livemart-vex-hugo/exampleSite"
